package gcode

import "testing"

func TestIsGcode(t *testing.T) {
	for _, name := range []string{"a.gcode", "A.GCO", "part.g"} {
		if !IsGcode(name) {
			t.Errorf("IsGcode(%q) = false, want true", name)
		}
	}
	for _, name := range []string{"a.stl", "a.3mf", "a.gcode.zip", "a"} {
		if IsGcode(name) {
			t.Errorf("IsGcode(%q) = true, want false", name)
		}
	}
}

// PrusaSlicer/OrcaSlicer: config block at the end, "; key = value".
const prusaSample = `; generated by PrusaSlicer 2.7.1+linux
G1 Z0.2
M104 S215
M140 S60
; prusaslicer_config = begin
; layer_height = 0.2
; first_layer_height = 0.2
; temperature = 210
; bed_temperature = 60
; fill_density = 15%
; nozzle_diameter = 0.4
; filament_type = PETG
; filament used [g] = 12.34
; filament used [mm] = 4123.5
; estimated printing time (normal mode) = 1h 23m 4s
; prusaslicer_config = end
`

func TestParsePrusa(t *testing.T) {
	parsed := Parse([]byte(prusaSample))
	assertFloat(t, parsed, "layer_height", 0.2)
	assertFloat(t, parsed, "first_layer_height", 0.2)
	assertFloat(t, parsed, "nozzle_temp", 210)
	assertFloat(t, parsed, "bed_temp", 60)
	assertFloat(t, parsed, "infill", 15)
	assertFloat(t, parsed, "nozzle_diameter", 0.4)
	assertFloat(t, parsed, "filament_used_g", 12.34)
	assertFloat(t, parsed, "filament_used_m", 4.12)
	if parsed["filament_type"] != "PETG" {
		t.Errorf("filament_type = %v, want PETG", parsed["filament_type"])
	}
	if parsed["print_time"] != "1h 23m 4s" {
		t.Errorf("print_time = %v, want 1h 23m 4s", parsed["print_time"])
	}
	if slicer, _ := parsed["slicer"].(string); slicer == "" {
		t.Errorf("slicer missing")
	}
}

// Cura: header, ";Key: value", TIME in seconds, temperature only as an M command.
const curaSample = `;FLAVOR:Marlin
;TIME:5030
;Filament used: 3.45m
;Layer height: 0.28
;Generated with Cura_SteamEngine 5.6.0
M140 S55
M104 S200
G1 X0 Y0
`

func TestParseCura(t *testing.T) {
	parsed := Parse([]byte(curaSample))
	assertFloat(t, parsed, "layer_height", 0.28)
	assertFloat(t, parsed, "filament_used_m", 3.45)
	assertFloat(t, parsed, "nozzle_temp", 200) // fallback from M104
	assertFloat(t, parsed, "bed_temp", 55)     // fallback from M140
	if parsed["print_time"] != "1h 23m" {      // 5030s → 1h 23m
		t.Errorf("print_time = %v, want 1h 23m", parsed["print_time"])
	}
	if slicer, _ := parsed["slicer"].(string); slicer == "" {
		t.Errorf("slicer missing")
	}
}

func assertFloat(t *testing.T, parsed map[string]any, key string, want float64) {
	t.Helper()
	value, ok := parsed[key]
	if !ok {
		t.Errorf("%s missing", key)
		return
	}
	number, ok := value.(float64)
	if !ok {
		t.Errorf("%s not float64: %T", key, value)
		return
	}
	if number != want {
		t.Errorf("%s = %v, want %v", key, number, want)
	}
}
