// Package config reads the runtime configuration from environment variables.
package config

import (
	"os"
	"strconv"
	"strings"
)

// DefaultAppKey is the built-in fallback for APP_KEY. It is intentionally public;
// running with it means all stored platform credentials are encrypted with a
// key that anyone can read from the source, so the app refuses to start on it
// (see cmd/app/main.go).
const DefaultAppKey = "meshdepot-default-key-32-chars!!"

// Config bundles all runtime settings of the app binary.
type Config struct {
	HTTPAddr        string // listen address of the HTTP server, e.g. ":8080". No default: the deployment (Compose) owns it and the app refuses to start without it (see cmd/app/main.go).
	AppKey          string // master key for credential encryption (Crypto).
	AppHTTPS        bool   // true enforces Secure cookies / HSTS.
	AppURL          string // allowed CORS origin; empty = mirror the request origin.
	DBPath          string // path to the SQLite file.
	BasePathData    string // root of the per-user storage tree; see internal/storage for the layout.
	ChromiumBin     string // path to the Chromium binary for rod.
	TorBin          string // path to the tor binary for the subprocess supervisor.
	LogLevel        string
	PlaywrightURL   string   // base URL of the bundled Firefox resolver. Defaults to the in-container loopback address; the app refuses to start when nothing answers there. Used for MMF download resolving via Firefox (CF bypass).
	PlaywrightToken string   // shared secret for the resolver. Generated by the container entrypoint when unset; only override when pointing PLAYWRIGHT_URL at an external resolver.
	TrustedProxies  []string // CIDRs/IPs of reverse proxies whose X-Real-IP header is believed. Empty = trust nobody (default, app exposed directly).
}

// Load reads the configuration from the environment with sensible defaults.
func Load() Config {
	return Config{
		HTTPAddr:        env("HTTP_ADDR", ""),
		AppKey:          env("APP_KEY", DefaultAppKey),
		AppHTTPS:        envBool("APP_HTTPS", false),
		AppURL:          env("APP_URL", ""),
		DBPath:          env("DB_PATH", "/data/meshdepot.db"),
		BasePathData:    env("BASE_PATH_DATA", "/data"),
		ChromiumBin:     env("CHROMIUM_BIN", "/usr/bin/chromium"),
		TorBin:          env("TOR_BIN", "tor"),
		LogLevel:        env("LOG_LEVEL", "all"),
		PlaywrightURL:   env("PLAYWRIGHT_URL", ""),
		PlaywrightToken: env("PLAYWRIGHT_TOKEN", ""),
		TrustedProxies:  envList("TRUSTED_PROXIES"),
	}
}

// envList splits a comma-separated environment variable into trimmed entries.
func envList(key string) []string {
	raw := strings.TrimSpace(os.Getenv(key))
	if raw == "" {
		return nil
	}
	var entries []string
	for _, part := range strings.Split(raw, ",") {
		if part = strings.TrimSpace(part); part != "" {
			entries = append(entries, part)
		}
	}
	return entries
}

// env returns the environment variable, or the default if it is empty/unset.
func env(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// envBool interprets an environment variable as a bool (1/true/yes).
func envBool(key string, defaultValue bool) bool {
	value := os.Getenv(key)
	if value == "" {
		return defaultValue
	}
	if parsed, failure := strconv.ParseBool(value); failure == nil {
		return parsed
	}
	return value == "1" || value == "yes" || value == "on"
}
